owner: GitNicksWeb
repo: status

sites:
  - name: Wasapi
    url: https://dash.wasapi.com.br/api
    maxResponseTime: 2000
    icon: https://raw.githubusercontent.com/GitNicksWeb/status/master/assets/favicon.ico
assignees:
  - alexbatista18
status-website:
  cname: status.wasapi.com.br
  logoUrl: https://raw.githubusercontent.com/GitNicksWeb/status/master/assets/wasapi-icon.png
  favicon: https://raw.githubusercontent.com/GitNicksWeb/status/master/assets/favicon.ico
  name: Wasapi Status
  introTitle: "About this site"
  introMessage: Welcome to Wasapi's real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://wasapi.com.br

